/*
 * AUTO-GENERATED by GenerateSource.py from Symbols.conf -- DO NOT EDIT.
 * Regenerate with:  python3 GenerateSource.py
 */

#include "../ZlibImport.h"
#include "../../2-callback/host/Invocation.h"

#include <cstddef>
#include <cstdint>

typedef struct {
    void *proc;     /* guest reentry dispatcher */
    void *callback; /* guest callback           */
    void *args;
    void *ret;
} ReentryArguments;

enum DispatcherIndex {
    DI_in_func,
    DI_out_func,
};

static void *gDispatchers[2];

/* Boundary between guest and host address space (set by HostRuntime): a
 * pointer below it is a guest function, at/above it is a host function. */
extern "C" void *qemu_address;

extern "C" void __initialize(void **args, void *ret) {
    (void) ret;
    for (int i = 0; i < sizeof(gDispatchers) / sizeof(gDispatchers[0]); i++) {
        gDispatchers[i] = *(void **) args[i];
    }
}

/* The C library calls these from host zlib; each re-enters the guest with
 * the saved guest callback. Single in-flight inflateBack per thread. */
static thread_local void *tlsIn;
static thread_local void *tlsOut;

static unsigned int host_in(void *in_desc, unsigned char **buf) {
    void *a[] = {&in_desc, &buf};
    unsigned int ret = 0;
    ReentryArguments ra = {gDispatchers[DI_in_func], tlsIn, a, &ret};
    lore::utils::Invocation::reenter(&ra);
    return ret;
}

static int host_out(void *out_desc, unsigned char *buf, unsigned int len) {
    void *a[] = {&out_desc, &buf, &len};
    int ret = 0;
    ReentryArguments ra = {gDispatchers[DI_out_func], tlsOut, a, &ret};
    lore::utils::Invocation::reenter(&ra);
    return ret;
}

extern "C" void __adler32(void **args, void *ret) {
    *(uLong *) ret = adler32(*(uLong *) args[0], *(const Bytef * *) args[1], *(uInt *) args[2]);
}

extern "C" void __adler32_combine(void **args, void *ret) {
    *(uLong *) ret = adler32_combine(*(uLong *) args[0], *(uLong *) args[1], *(z_off_t *) args[2]);
}

extern "C" void __adler32_combine64(void **args, void *ret) {
    *(uLong *) ret = adler32_combine64(*(uLong *) args[0], *(uLong *) args[1], *(z_off64_t *) args[2]);
}

extern "C" void __adler32_z(void **args, void *ret) {
    *(uLong *) ret = adler32_z(*(uLong *) args[0], *(const Bytef * *) args[1], *(z_size_t *) args[2]);
}

extern "C" void __compress(void **args, void *ret) {
    *(int *) ret = compress(*(Bytef * *) args[0], *(uLongf * *) args[1], *(const Bytef * *) args[2], *(uLong *) args[3]);
}

extern "C" void __compress2(void **args, void *ret) {
    *(int *) ret = compress2(*(Bytef * *) args[0], *(uLongf * *) args[1], *(const Bytef * *) args[2], *(uLong *) args[3], *(int *) args[4]);
}

extern "C" void __compressBound(void **args, void *ret) {
    *(uLong *) ret = compressBound(*(uLong *) args[0]);
}

extern "C" void __crc32(void **args, void *ret) {
    *(uLong *) ret = crc32(*(uLong *) args[0], *(const Bytef * *) args[1], *(uInt *) args[2]);
}

extern "C" void __crc32_combine(void **args, void *ret) {
    *(uLong *) ret = crc32_combine(*(uLong *) args[0], *(uLong *) args[1], *(z_off_t *) args[2]);
}

extern "C" void __crc32_combine64(void **args, void *ret) {
    *(uLong *) ret = crc32_combine64(*(uLong *) args[0], *(uLong *) args[1], *(z_off64_t *) args[2]);
}

extern "C" void __deflate(void **args, void *ret) {
    *(int *) ret = deflate(*(z_streamp *) args[0], *(int *) args[1]);
}

extern "C" void __deflateBound(void **args, void *ret) {
    *(uLong *) ret = deflateBound(*(z_streamp *) args[0], *(uLong *) args[1]);
}

extern "C" void __deflateCopy(void **args, void *ret) {
    *(int *) ret = deflateCopy(*(z_streamp *) args[0], *(z_streamp *) args[1]);
}

extern "C" void __deflateEnd(void **args, void *ret) {
    *(int *) ret = deflateEnd(*(z_streamp *) args[0]);
}

extern "C" void __deflateGetDictionary(void **args, void *ret) {
    *(int *) ret = deflateGetDictionary(*(z_streamp *) args[0], *(Bytef * *) args[1], *(uInt * *) args[2]);
}

extern "C" void __deflateInit2_(void **args, void *ret) {
    *(int *) ret = deflateInit2_(*(z_streamp *) args[0], *(int *) args[1], *(int *) args[2], *(int *) args[3], *(int *) args[4], *(int *) args[5], *(const char * *) args[6], *(int *) args[7]);
}

extern "C" void __deflateInit_(void **args, void *ret) {
    *(int *) ret = deflateInit_(*(z_streamp *) args[0], *(int *) args[1], *(const char * *) args[2], *(int *) args[3]);
}

extern "C" void __deflateParams(void **args, void *ret) {
    *(int *) ret = deflateParams(*(z_streamp *) args[0], *(int *) args[1], *(int *) args[2]);
}

extern "C" void __deflatePending(void **args, void *ret) {
    *(int *) ret = deflatePending(*(z_streamp *) args[0], *(unsigned int * *) args[1], *(int * *) args[2]);
}

extern "C" void __deflatePrime(void **args, void *ret) {
    *(int *) ret = deflatePrime(*(z_streamp *) args[0], *(int *) args[1], *(int *) args[2]);
}

extern "C" void __deflateReset(void **args, void *ret) {
    *(int *) ret = deflateReset(*(z_streamp *) args[0]);
}

extern "C" void __deflateResetKeep(void **args, void *ret) {
    *(int *) ret = deflateResetKeep(*(z_streamp *) args[0]);
}

extern "C" void __deflateSetDictionary(void **args, void *ret) {
    *(int *) ret = deflateSetDictionary(*(z_streamp *) args[0], *(const Bytef * *) args[1], *(uInt *) args[2]);
}

extern "C" void __deflateSetHeader(void **args, void *ret) {
    *(int *) ret = deflateSetHeader(*(z_streamp *) args[0], *(gz_headerp *) args[1]);
}

extern "C" void __deflateTune(void **args, void *ret) {
    *(int *) ret = deflateTune(*(z_streamp *) args[0], *(int *) args[1], *(int *) args[2], *(int *) args[3], *(int *) args[4]);
}

extern "C" void __get_crc_table(void **args, void *ret) {
    (void) args;
    *(const z_crc_t * *) ret = get_crc_table();
}

extern "C" void __gzbuffer(void **args, void *ret) {
    *(int *) ret = gzbuffer(*(gzFile *) args[0], *(unsigned int *) args[1]);
}

extern "C" void __gzclearerr(void **args, void *ret) {
    (void) ret;
    gzclearerr(*(gzFile *) args[0]);
}

extern "C" void __gzclose(void **args, void *ret) {
    *(int *) ret = gzclose(*(gzFile *) args[0]);
}

extern "C" void __gzclose_r(void **args, void *ret) {
    *(int *) ret = gzclose_r(*(gzFile *) args[0]);
}

extern "C" void __gzclose_w(void **args, void *ret) {
    *(int *) ret = gzclose_w(*(gzFile *) args[0]);
}

extern "C" void __gzdirect(void **args, void *ret) {
    *(int *) ret = gzdirect(*(gzFile *) args[0]);
}

extern "C" void __gzdopen(void **args, void *ret) {
    *(gzFile *) ret = gzdopen(*(int *) args[0], *(const char * *) args[1]);
}

extern "C" void __gzeof(void **args, void *ret) {
    *(int *) ret = gzeof(*(gzFile *) args[0]);
}

extern "C" void __gzerror(void **args, void *ret) {
    *(const char * *) ret = gzerror(*(gzFile *) args[0], *(int * *) args[1]);
}

extern "C" void __gzflush(void **args, void *ret) {
    *(int *) ret = gzflush(*(gzFile *) args[0], *(int *) args[1]);
}

extern "C" void __gzfread(void **args, void *ret) {
    *(z_size_t *) ret = gzfread(*(voidp *) args[0], *(z_size_t *) args[1], *(z_size_t *) args[2], *(gzFile *) args[3]);
}

extern "C" void __gzfwrite(void **args, void *ret) {
    *(z_size_t *) ret = gzfwrite(*(voidpc *) args[0], *(z_size_t *) args[1], *(z_size_t *) args[2], *(gzFile *) args[3]);
}

extern "C" void __gzgetc(void **args, void *ret) {
    *(int *) ret = gzgetc(*(gzFile *) args[0]);
}

extern "C" void __gzgetc_(void **args, void *ret) {
    *(int *) ret = gzgetc_(*(gzFile *) args[0]);
}

extern "C" void __gzgets(void **args, void *ret) {
    *(char * *) ret = gzgets(*(gzFile *) args[0], *(char * *) args[1], *(int *) args[2]);
}

extern "C" void __gzoffset(void **args, void *ret) {
    *(z_off_t *) ret = gzoffset(*(gzFile *) args[0]);
}

extern "C" void __gzoffset64(void **args, void *ret) {
    *(z_off64_t *) ret = gzoffset64(*(gzFile *) args[0]);
}

extern "C" void __gzopen(void **args, void *ret) {
    *(gzFile *) ret = gzopen(*(const char * *) args[0], *(const char * *) args[1]);
}

extern "C" void __gzopen64(void **args, void *ret) {
    *(gzFile *) ret = gzopen64(*(const char * *) args[0], *(const char * *) args[1]);
}

extern "C" void __gzputc(void **args, void *ret) {
    *(int *) ret = gzputc(*(gzFile *) args[0], *(int *) args[1]);
}

extern "C" void __gzputs(void **args, void *ret) {
    *(int *) ret = gzputs(*(gzFile *) args[0], *(const char * *) args[1]);
}

extern "C" void __gzread(void **args, void *ret) {
    *(int *) ret = gzread(*(gzFile *) args[0], *(voidp *) args[1], *(unsigned int *) args[2]);
}

extern "C" void __gzrewind(void **args, void *ret) {
    *(int *) ret = gzrewind(*(gzFile *) args[0]);
}

extern "C" void __gzseek(void **args, void *ret) {
    *(z_off_t *) ret = gzseek(*(gzFile *) args[0], *(z_off_t *) args[1], *(int *) args[2]);
}

extern "C" void __gzseek64(void **args, void *ret) {
    *(z_off64_t *) ret = gzseek64(*(gzFile *) args[0], *(z_off64_t *) args[1], *(int *) args[2]);
}

extern "C" void __gzsetparams(void **args, void *ret) {
    *(int *) ret = gzsetparams(*(gzFile *) args[0], *(int *) args[1], *(int *) args[2]);
}

extern "C" void __gztell(void **args, void *ret) {
    *(z_off_t *) ret = gztell(*(gzFile *) args[0]);
}

extern "C" void __gztell64(void **args, void *ret) {
    *(z_off64_t *) ret = gztell64(*(gzFile *) args[0]);
}

extern "C" void __gzungetc(void **args, void *ret) {
    *(int *) ret = gzungetc(*(int *) args[0], *(gzFile *) args[1]);
}

extern "C" void __gzwrite(void **args, void *ret) {
    *(int *) ret = gzwrite(*(gzFile *) args[0], *(voidpc *) args[1], *(unsigned int *) args[2]);
}

extern "C" void __inflate(void **args, void *ret) {
    *(int *) ret = inflate(*(z_streamp *) args[0], *(int *) args[1]);
}

extern "C" void __inflateBackEnd(void **args, void *ret) {
    *(int *) ret = inflateBackEnd(*(z_streamp *) args[0]);
}

extern "C" void __inflateBackInit_(void **args, void *ret) {
    *(int *) ret = inflateBackInit_(*(z_streamp *) args[0], *(int *) args[1], *(unsigned char * *) args[2], *(const char * *) args[3], *(int *) args[4]);
}

extern "C" void __inflateCodesUsed(void **args, void *ret) {
    *(unsigned long *) ret = inflateCodesUsed(*(z_streamp *) args[0]);
}

extern "C" void __inflateCopy(void **args, void *ret) {
    *(int *) ret = inflateCopy(*(z_streamp *) args[0], *(z_streamp *) args[1]);
}

extern "C" void __inflateEnd(void **args, void *ret) {
    *(int *) ret = inflateEnd(*(z_streamp *) args[0]);
}

extern "C" void __inflateGetDictionary(void **args, void *ret) {
    *(int *) ret = inflateGetDictionary(*(z_streamp *) args[0], *(Bytef * *) args[1], *(uInt * *) args[2]);
}

extern "C" void __inflateGetHeader(void **args, void *ret) {
    *(int *) ret = inflateGetHeader(*(z_streamp *) args[0], *(gz_headerp *) args[1]);
}

extern "C" void __inflateInit2_(void **args, void *ret) {
    *(int *) ret = inflateInit2_(*(z_streamp *) args[0], *(int *) args[1], *(const char * *) args[2], *(int *) args[3]);
}

extern "C" void __inflateInit_(void **args, void *ret) {
    *(int *) ret = inflateInit_(*(z_streamp *) args[0], *(const char * *) args[1], *(int *) args[2]);
}

extern "C" void __inflateMark(void **args, void *ret) {
    *(long *) ret = inflateMark(*(z_streamp *) args[0]);
}

extern "C" void __inflatePrime(void **args, void *ret) {
    *(int *) ret = inflatePrime(*(z_streamp *) args[0], *(int *) args[1], *(int *) args[2]);
}

extern "C" void __inflateReset(void **args, void *ret) {
    *(int *) ret = inflateReset(*(z_streamp *) args[0]);
}

extern "C" void __inflateReset2(void **args, void *ret) {
    *(int *) ret = inflateReset2(*(z_streamp *) args[0], *(int *) args[1]);
}

extern "C" void __inflateResetKeep(void **args, void *ret) {
    *(int *) ret = inflateResetKeep(*(z_streamp *) args[0]);
}

extern "C" void __inflateSetDictionary(void **args, void *ret) {
    *(int *) ret = inflateSetDictionary(*(z_streamp *) args[0], *(const Bytef * *) args[1], *(uInt *) args[2]);
}

extern "C" void __inflateSync(void **args, void *ret) {
    *(int *) ret = inflateSync(*(z_streamp *) args[0]);
}

extern "C" void __inflateSyncPoint(void **args, void *ret) {
    *(int *) ret = inflateSyncPoint(*(z_streamp *) args[0]);
}

extern "C" void __inflateUndermine(void **args, void *ret) {
    *(int *) ret = inflateUndermine(*(z_streamp *) args[0], *(int *) args[1]);
}

extern "C" void __inflateValidate(void **args, void *ret) {
    *(int *) ret = inflateValidate(*(z_streamp *) args[0], *(int *) args[1]);
}

extern "C" void __uncompress(void **args, void *ret) {
    *(int *) ret = uncompress(*(Bytef * *) args[0], *(uLongf * *) args[1], *(const Bytef * *) args[2], *(uLong *) args[3]);
}

extern "C" void __uncompress2(void **args, void *ret) {
    *(int *) ret = uncompress2(*(Bytef * *) args[0], *(uLongf * *) args[1], *(const Bytef * *) args[2], *(uLong * *) args[3]);
}

extern "C" void __zError(void **args, void *ret) {
    *(const char * *) ret = zError(*(int *) args[0]);
}

extern "C" void __zlibCompileFlags(void **args, void *ret) {
    (void) args;
    *(uLong *) ret = zlibCompileFlags();
}

extern "C" void __zlibVersion(void **args, void *ret) {
    (void) args;
    *(const char * *) ret = zlibVersion();
}

extern "C" void __inflateBack(void **args, void *ret) {
    z_streamp strm = *(z_streamp *) args[0];
    void *in       = *(void **)     args[1];
    void *in_desc  = *(void **)     args[2];
    void *out      = *(void **)     args[3];
    void *out_desc = *(void **)     args[4];

    /* Only a guest callback needs to be routed through a trampoline; a host
     * function pointer is called directly. tls is set right before the call
     * and only read when the matching trampoline is installed, so it needs
     * no save/restore. */
    in_func hin = (in_func) in;
    if ((uintptr_t) in < (uintptr_t) qemu_address) {
        tlsIn = in;
        hin = host_in;
    }
    out_func hout = (out_func) out;
    if ((uintptr_t) out < (uintptr_t) qemu_address) {
        tlsOut = out;
        hout = host_out;
    }
    *(int *) ret = inflateBack(strm, hin, in_desc, hout, out_desc);
}
