/*
 * AUTO-GENERATED by GenerateSource.py -- DO NOT EDIT.
 * Regenerate with:  python3 GenerateSource.py
 */

#include "../GLImport.h"

#include <cstddef>

extern "C" void __glBegin(void **args, void *ret) {
    (void) ret;
    glBegin(*(GLenum *) args[0]);
}

extern "C" void __glBlendFunc(void **args, void *ret) {
    (void) ret;
    glBlendFunc(*(GLenum *) args[0], *(GLenum *) args[1]);
}

extern "C" void __glClear(void **args, void *ret) {
    (void) ret;
    glClear(*(GLbitfield *) args[0]);
}

extern "C" void __glClearColor(void **args, void *ret) {
    (void) ret;
    glClearColor(*(GLclampf *) args[0], *(GLclampf *) args[1], *(GLclampf *) args[2], *(GLclampf *) args[3]);
}

extern "C" void __glColor4f(void **args, void *ret) {
    (void) ret;
    glColor4f(*(GLfloat *) args[0], *(GLfloat *) args[1], *(GLfloat *) args[2], *(GLfloat *) args[3]);
}

extern "C" void __glDisable(void **args, void *ret) {
    (void) ret;
    glDisable(*(GLenum *) args[0]);
}

extern "C" void __glEnable(void **args, void *ret) {
    (void) ret;
    glEnable(*(GLenum *) args[0]);
}

extern "C" void __glEnd(void **args, void *ret) {
    (void) args;
    (void) ret;
    glEnd();
}

extern "C" void __glFrustum(void **args, void *ret) {
    (void) ret;
    glFrustum(*(GLdouble *) args[0], *(GLdouble *) args[1], *(GLdouble *) args[2], *(GLdouble *) args[3], *(GLdouble *) args[4], *(GLdouble *) args[5]);
}

extern "C" void __glHint(void **args, void *ret) {
    (void) ret;
    glHint(*(GLenum *) args[0], *(GLenum *) args[1]);
}

extern "C" void __glLineWidth(void **args, void *ret) {
    (void) ret;
    glLineWidth(*(GLfloat *) args[0]);
}

extern "C" void __glLoadIdentity(void **args, void *ret) {
    (void) args;
    (void) ret;
    glLoadIdentity();
}

extern "C" void __glMatrixMode(void **args, void *ret) {
    (void) ret;
    glMatrixMode(*(GLenum *) args[0]);
}

extern "C" void __glPointSize(void **args, void *ret) {
    (void) ret;
    glPointSize(*(GLfloat *) args[0]);
}

extern "C" void __glPopMatrix(void **args, void *ret) {
    (void) args;
    (void) ret;
    glPopMatrix();
}

extern "C" void __glPushMatrix(void **args, void *ret) {
    (void) args;
    (void) ret;
    glPushMatrix();
}

extern "C" void __glRotatef(void **args, void *ret) {
    (void) ret;
    glRotatef(*(GLfloat *) args[0], *(GLfloat *) args[1], *(GLfloat *) args[2], *(GLfloat *) args[3]);
}

extern "C" void __glTranslatef(void **args, void *ret) {
    (void) ret;
    glTranslatef(*(GLfloat *) args[0], *(GLfloat *) args[1], *(GLfloat *) args[2]);
}

extern "C" void __glVertex3f(void **args, void *ret) {
    (void) ret;
    glVertex3f(*(GLfloat *) args[0], *(GLfloat *) args[1], *(GLfloat *) args[2]);
}

extern "C" void __glViewport(void **args, void *ret) {
    (void) ret;
    glViewport(*(GLint *) args[0], *(GLint *) args[1], *(GLsizei *) args[2], *(GLsizei *) args[3]);
}

extern "C" void __glXChooseVisual(void **args, void *ret) {
    *(XVisualInfo * *) ret = glXChooseVisual(*(Display * *) args[0], *(int *) args[1], *(int * *) args[2]);
}

extern "C" void __glXCreateContext(void **args, void *ret) {
    *(GLXContext *) ret = glXCreateContext(*(Display * *) args[0], *(XVisualInfo * *) args[1], *(GLXContext *) args[2], *(int *) args[3]);
}

extern "C" void __glXDestroyContext(void **args, void *ret) {
    (void) ret;
    glXDestroyContext(*(Display * *) args[0], *(GLXContext *) args[1]);
}

extern "C" void __glXMakeCurrent(void **args, void *ret) {
    *(int *) ret = glXMakeCurrent(*(Display * *) args[0], *(GLXDrawable *) args[1], *(GLXContext *) args[2]);
}

extern "C" void __glXSwapBuffers(void **args, void *ret) {
    (void) ret;
    glXSwapBuffers(*(Display * *) args[0], *(GLXDrawable *) args[1]);
}
