/*
 * AUTO-GENERATED by GenerateSource.py -- DO NOT EDIT.
 * Regenerate with:  python3 GenerateSource.py
 */

#include "../X11Import.h"

#include <cstddef>

extern "C" void __XCloseDisplay(void **args, void *ret) {
    *(int *) ret = XCloseDisplay(*(Display * *) args[0]);
}

extern "C" void __XCreateColormap(void **args, void *ret) {
    *(Colormap *) ret = XCreateColormap(*(Display * *) args[0], *(Window *) args[1], *(Visual * *) args[2], *(int *) args[3]);
}

extern "C" void __XCreateWindow(void **args, void *ret) {
    *(Window *) ret = XCreateWindow(*(Display * *) args[0], *(Window *) args[1], *(int *) args[2], *(int *) args[3], *(unsigned int *) args[4], *(unsigned int *) args[5], *(unsigned int *) args[6], *(int *) args[7], *(unsigned int *) args[8], *(Visual * *) args[9], *(unsigned long *) args[10], *(XSetWindowAttributes * *) args[11]);
}

extern "C" void __XDestroyWindow(void **args, void *ret) {
    *(int *) ret = XDestroyWindow(*(Display * *) args[0], *(Window *) args[1]);
}

extern "C" void __XInternAtom(void **args, void *ret) {
    *(Atom *) ret = XInternAtom(*(Display * *) args[0], *(const char * *) args[1], *(int *) args[2]);
}

extern "C" void __XLookupKeysym(void **args, void *ret) {
    *(KeySym *) ret = XLookupKeysym(*(XKeyEvent * *) args[0], *(int *) args[1]);
}

extern "C" void __XMapWindow(void **args, void *ret) {
    *(int *) ret = XMapWindow(*(Display * *) args[0], *(Window *) args[1]);
}

extern "C" void __XNextEvent(void **args, void *ret) {
    *(int *) ret = XNextEvent(*(Display * *) args[0], *(XEvent * *) args[1]);
}

extern "C" void __XOpenDisplay(void **args, void *ret) {
    *(Display * *) ret = XOpenDisplay(*(const char * *) args[0]);
}

extern "C" void __XPending(void **args, void *ret) {
    *(int *) ret = XPending(*(Display * *) args[0]);
}

extern "C" void __XSetWMProtocols(void **args, void *ret) {
    *(int *) ret = XSetWMProtocols(*(Display * *) args[0], *(Window *) args[1], *(Atom * *) args[2], *(int *) args[3]);
}

extern "C" void __XStoreName(void **args, void *ret) {
    *(int *) ret = XStoreName(*(Display * *) args[0], *(Window *) args[1], *(const char * *) args[2]);
}
