#!/usr/bin/env python3
"""
Generate 2-callback-style pass-through thunks for the X11 and GL functions used
by Program.cpp. Two thunk pairs are produced:

  guest/X11Thunk.c  + host/X11ThunkHost.cpp   (drop-in libX11 -> host Xlib)
  guest/GLThunk.c   + host/GLThunkHost.cpp     (drop-in libGL  -> host GL/GLX)

Every function these programs use is pure data pass-through (no callbacks, no
varargs), so each guest stub packs args[] and calls InvokeProc, and each host
adapter unpacks args[] and calls the REAL host function.
"""
import json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CLANG = os.environ.get("CLANG", "clang-20")

WARNING = [
    "/*",
    " * AUTO-GENERATED by GenerateSource.py -- DO NOT EDIT.",
    " * Regenerate with:  python3 GenerateSource.py",
    " */",
    "",
]

THUNKS = [
    {"name": "X11", "header": "X11Import.h", "conf": "X11Symbols.conf",
     "guest_out": "guest/X11Thunk.c", "host_out": "host/X11ThunkHost.cpp",
     "host_lib": "libX11ThunkHost.so"},
    {"name": "GL", "header": "GLImport.h", "conf": "GLSymbols.conf",
     "guest_out": "guest/GLThunk.c", "host_out": "host/GLThunkHost.cpp",
     "host_lib": "libGLThunkHost.so"},
]


def load_symbols(conf):
    syms, inblock = [], False
    for line in open(os.path.join(HERE, conf)):
        s = line.strip()
        if s == "[Function]":
            inblock = True
            continue
        if inblock and s:
            syms.append(s)
    return syms


def load_funcs(header, symset):
    cmd = [CLANG, "-x", "c", "-Xclang", "-ast-dump=json", "-fsyntax-only",
           os.path.join(HERE, header)]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        sys.exit("clang AST dump failed for " + header)
    d = json.loads(proc.stdout)
    funcs = {}
    for n in d.get("inner", []):
        if n.get("kind") == "FunctionDecl" and n.get("name") in symset:
            qt = n["type"]["qualType"]
            ret = qt[:qt.index("(")].rstrip()
            params = [c["type"]["qualType"]
                      for c in n.get("inner", []) if c.get("kind") == "ParmVarDecl"]
            funcs[n["name"]] = (ret, params)
    return funcs


def gen_guest(cfg, syms, funcs):
    L = list(WARNING)
    w = L.append
    w('#include "../%s"' % cfg["header"])
    w('#include "../../2-callback/guest/GuestRuntime.h"')
    w("")
    w("#include <dlfcn.h>")
    w("#include <stddef.h>")
    w("#include <stdio.h>")
    w("#include <stdlib.h>")
    w("")
    w("enum HostProcIndex {")
    for f in syms:
        w("    HP_%s," % f)
    w("    HP_COUNT,")
    w("};")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    void *proc;")
    w("} HostProc;")
    w("")
    w("static HostProc hostProcs[HP_COUNT] = {")
    for f in syms:
        w('    [HP_%s] = {"__%s", NULL},' % (f, f))
    w("};")
    w("")
    w("static void *hostLibHandle;")
    w("")
    w("static __attribute__((constructor(102))) void init(void) {")
    w('    hostLibHandle = LoadLibrary("%s", RTLD_NOW);' % cfg["host_lib"])
    w("    if (hostLibHandle == NULL) {")
    w('        fprintf(stderr, "%s: failed to load %s: %%s\\n", GetLibraryError());'
      % (cfg["name"], cfg["host_lib"]))
    w("        abort();")
    w("    }")
    w("")
    w("    for (int i = 0; i < HP_COUNT; i++) {")
    w("        hostProcs[i].proc = GetProcAddress(hostLibHandle, hostProcs[i].name);")
    w("        if (hostProcs[i].proc == NULL) {")
    w('            fprintf(stderr, "%s: failed to resolve %%s: %%s\\n", hostProcs[i].name,'
      % cfg["name"])
    w("                    GetLibraryError());")
    w("            abort();")
    w("        }")
    w("    }")
    w("}")
    w("")
    for f in syms:
        ret, params = funcs[f]
        is_void = (ret == "void")
        names = ["a%d" % i for i in range(len(params))]
        sig = ", ".join("%s %s" % (p, n) for p, n in zip(params, names)) or "void"
        w("%s %s(%s) {" % (ret, f, sig))
        if params:
            w("    void *args[] = {%s};" % ", ".join("&%s" % n for n in names))
        argref = "args" if params else "NULL"
        if is_void:
            w("    InvocationArguments ia = {")
            w("        .proc = hostProcs[HP_%s].proc," % f)
            w("        .args = %s," % argref)
            w("        .ret  = NULL,")
            w("    };")
            w("    InvokeProc(&ia);")
        else:
            w("    %s ret;" % ret)
            w("    InvocationArguments ia = {")
            w("        .proc = hostProcs[HP_%s].proc," % f)
            w("        .args = %s," % argref)
            w("        .ret  = &ret,")
            w("    };")
            w("    InvokeProc(&ia);")
            w("    return ret;")
        w("}")
        w("")
    return "\n".join(L)


def gen_host(cfg, syms, funcs):
    L = list(WARNING)
    w = L.append
    w('#include "../%s"' % cfg["header"])
    w("")
    w("#include <cstddef>")
    w("")
    for f in syms:
        ret, params = funcs[f]
        is_void = (ret == "void")
        call = ", ".join("*(%s *) args[%d]" % (p, i) for i, p in enumerate(params))
        w('extern "C" void __%s(void **args, void *ret) {' % f)
        if not params:
            w("    (void) args;")
        if is_void:
            w("    (void) ret;")
            w("    %s(%s);" % (f, call))
        else:
            w("    *(%s *) ret = %s(%s);" % (ret, f, call))
        w("}")
        w("")
    return "\n".join(L)


def main():
    os.makedirs(os.path.join(HERE, "guest"), exist_ok=True)
    os.makedirs(os.path.join(HERE, "host"), exist_ok=True)
    for cfg in THUNKS:
        syms = load_symbols(cfg["conf"])
        funcs = load_funcs(cfg["header"], set(syms))
        missing = [s for s in syms if s not in funcs]
        if missing:
            sys.exit("%s unresolved (macro or missing decl?): %s" % (cfg["name"], missing))
        open(os.path.join(HERE, cfg["guest_out"]), "w").write(gen_guest(cfg, syms, funcs))
        open(os.path.join(HERE, cfg["host_out"]), "w").write(gen_host(cfg, syms, funcs))
        print("%s: %d functions -> %s, %s"
              % (cfg["name"], len(syms), cfg["guest_out"], cfg["host_out"]))


if __name__ == "__main__":
    main()
