[Function]
glBegin
glBlendFunc
glClear
glClearColor
glColor4f
glDisable
glEnable
glEnd
glFrustum
glHint
glLineWidth
glLoadIdentity
glMatrixMode
glPointSize
glPopMatrix
glPushMatrix
glRotatef
glTranslatef
glVertex3f
glViewport
glXChooseVisual
glXCreateContext
glXDestroyContext
glXMakeCurrent
glXSwapBuffers
