/*
 * AUTO-GENERATED by GenerateSource.py from Symbols.conf -- DO NOT EDIT.
 * Regenerate with:  python3 GenerateSource.py
 */

#include "../ZlibImport.h"
#include "../../2-callback/guest/GuestRuntime.h"

#include <dlfcn.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

enum HostProcIndex {
    HZ___initialize,
    HZ_adler32,
    HZ_adler32_combine,
    HZ_adler32_combine64,
    HZ_adler32_z,
    HZ_compress,
    HZ_compress2,
    HZ_compressBound,
    HZ_crc32,
    HZ_crc32_combine,
    HZ_crc32_combine64,
    HZ_deflate,
    HZ_deflateBound,
    HZ_deflateCopy,
    HZ_deflateEnd,
    HZ_deflateGetDictionary,
    HZ_deflateInit2_,
    HZ_deflateInit_,
    HZ_deflateParams,
    HZ_deflatePending,
    HZ_deflatePrime,
    HZ_deflateReset,
    HZ_deflateResetKeep,
    HZ_deflateSetDictionary,
    HZ_deflateSetHeader,
    HZ_deflateTune,
    HZ_get_crc_table,
    HZ_gzbuffer,
    HZ_gzclearerr,
    HZ_gzclose,
    HZ_gzclose_r,
    HZ_gzclose_w,
    HZ_gzdirect,
    HZ_gzdopen,
    HZ_gzeof,
    HZ_gzerror,
    HZ_gzflush,
    HZ_gzfread,
    HZ_gzfwrite,
    HZ_gzgetc,
    HZ_gzgetc_,
    HZ_gzgets,
    HZ_gzoffset,
    HZ_gzoffset64,
    HZ_gzopen,
    HZ_gzopen64,
    HZ_gzputc,
    HZ_gzputs,
    HZ_gzread,
    HZ_gzrewind,
    HZ_gzseek,
    HZ_gzseek64,
    HZ_gzsetparams,
    HZ_gztell,
    HZ_gztell64,
    HZ_gzungetc,
    HZ_gzwrite,
    HZ_inflate,
    HZ_inflateBack,
    HZ_inflateBackEnd,
    HZ_inflateBackInit_,
    HZ_inflateCodesUsed,
    HZ_inflateCopy,
    HZ_inflateEnd,
    HZ_inflateGetDictionary,
    HZ_inflateGetHeader,
    HZ_inflateInit2_,
    HZ_inflateInit_,
    HZ_inflateMark,
    HZ_inflatePrime,
    HZ_inflateReset,
    HZ_inflateReset2,
    HZ_inflateResetKeep,
    HZ_inflateSetDictionary,
    HZ_inflateSync,
    HZ_inflateSyncPoint,
    HZ_inflateUndermine,
    HZ_inflateValidate,
    HZ_uncompress,
    HZ_uncompress2,
    HZ_zError,
    HZ_zlibCompileFlags,
    HZ_zlibVersion,
    HZ_COUNT,
};

typedef struct {
    const char *name;
    void *proc;
} HostProc;

static HostProc hostProcs[HZ_COUNT] = {
    [HZ___initialize] = {"__initialize", NULL},
    [HZ_adler32] = {"__adler32", NULL},
    [HZ_adler32_combine] = {"__adler32_combine", NULL},
    [HZ_adler32_combine64] = {"__adler32_combine64", NULL},
    [HZ_adler32_z] = {"__adler32_z", NULL},
    [HZ_compress] = {"__compress", NULL},
    [HZ_compress2] = {"__compress2", NULL},
    [HZ_compressBound] = {"__compressBound", NULL},
    [HZ_crc32] = {"__crc32", NULL},
    [HZ_crc32_combine] = {"__crc32_combine", NULL},
    [HZ_crc32_combine64] = {"__crc32_combine64", NULL},
    [HZ_deflate] = {"__deflate", NULL},
    [HZ_deflateBound] = {"__deflateBound", NULL},
    [HZ_deflateCopy] = {"__deflateCopy", NULL},
    [HZ_deflateEnd] = {"__deflateEnd", NULL},
    [HZ_deflateGetDictionary] = {"__deflateGetDictionary", NULL},
    [HZ_deflateInit2_] = {"__deflateInit2_", NULL},
    [HZ_deflateInit_] = {"__deflateInit_", NULL},
    [HZ_deflateParams] = {"__deflateParams", NULL},
    [HZ_deflatePending] = {"__deflatePending", NULL},
    [HZ_deflatePrime] = {"__deflatePrime", NULL},
    [HZ_deflateReset] = {"__deflateReset", NULL},
    [HZ_deflateResetKeep] = {"__deflateResetKeep", NULL},
    [HZ_deflateSetDictionary] = {"__deflateSetDictionary", NULL},
    [HZ_deflateSetHeader] = {"__deflateSetHeader", NULL},
    [HZ_deflateTune] = {"__deflateTune", NULL},
    [HZ_get_crc_table] = {"__get_crc_table", NULL},
    [HZ_gzbuffer] = {"__gzbuffer", NULL},
    [HZ_gzclearerr] = {"__gzclearerr", NULL},
    [HZ_gzclose] = {"__gzclose", NULL},
    [HZ_gzclose_r] = {"__gzclose_r", NULL},
    [HZ_gzclose_w] = {"__gzclose_w", NULL},
    [HZ_gzdirect] = {"__gzdirect", NULL},
    [HZ_gzdopen] = {"__gzdopen", NULL},
    [HZ_gzeof] = {"__gzeof", NULL},
    [HZ_gzerror] = {"__gzerror", NULL},
    [HZ_gzflush] = {"__gzflush", NULL},
    [HZ_gzfread] = {"__gzfread", NULL},
    [HZ_gzfwrite] = {"__gzfwrite", NULL},
    [HZ_gzgetc] = {"__gzgetc", NULL},
    [HZ_gzgetc_] = {"__gzgetc_", NULL},
    [HZ_gzgets] = {"__gzgets", NULL},
    [HZ_gzoffset] = {"__gzoffset", NULL},
    [HZ_gzoffset64] = {"__gzoffset64", NULL},
    [HZ_gzopen] = {"__gzopen", NULL},
    [HZ_gzopen64] = {"__gzopen64", NULL},
    [HZ_gzputc] = {"__gzputc", NULL},
    [HZ_gzputs] = {"__gzputs", NULL},
    [HZ_gzread] = {"__gzread", NULL},
    [HZ_gzrewind] = {"__gzrewind", NULL},
    [HZ_gzseek] = {"__gzseek", NULL},
    [HZ_gzseek64] = {"__gzseek64", NULL},
    [HZ_gzsetparams] = {"__gzsetparams", NULL},
    [HZ_gztell] = {"__gztell", NULL},
    [HZ_gztell64] = {"__gztell64", NULL},
    [HZ_gzungetc] = {"__gzungetc", NULL},
    [HZ_gzwrite] = {"__gzwrite", NULL},
    [HZ_inflate] = {"__inflate", NULL},
    [HZ_inflateBack] = {"__inflateBack", NULL},
    [HZ_inflateBackEnd] = {"__inflateBackEnd", NULL},
    [HZ_inflateBackInit_] = {"__inflateBackInit_", NULL},
    [HZ_inflateCodesUsed] = {"__inflateCodesUsed", NULL},
    [HZ_inflateCopy] = {"__inflateCopy", NULL},
    [HZ_inflateEnd] = {"__inflateEnd", NULL},
    [HZ_inflateGetDictionary] = {"__inflateGetDictionary", NULL},
    [HZ_inflateGetHeader] = {"__inflateGetHeader", NULL},
    [HZ_inflateInit2_] = {"__inflateInit2_", NULL},
    [HZ_inflateInit_] = {"__inflateInit_", NULL},
    [HZ_inflateMark] = {"__inflateMark", NULL},
    [HZ_inflatePrime] = {"__inflatePrime", NULL},
    [HZ_inflateReset] = {"__inflateReset", NULL},
    [HZ_inflateReset2] = {"__inflateReset2", NULL},
    [HZ_inflateResetKeep] = {"__inflateResetKeep", NULL},
    [HZ_inflateSetDictionary] = {"__inflateSetDictionary", NULL},
    [HZ_inflateSync] = {"__inflateSync", NULL},
    [HZ_inflateSyncPoint] = {"__inflateSyncPoint", NULL},
    [HZ_inflateUndermine] = {"__inflateUndermine", NULL},
    [HZ_inflateValidate] = {"__inflateValidate", NULL},
    [HZ_uncompress] = {"__uncompress", NULL},
    [HZ_uncompress2] = {"__uncompress2", NULL},
    [HZ_zError] = {"__zError", NULL},
    [HZ_zlibCompileFlags] = {"__zlibCompileFlags", NULL},
    [HZ_zlibVersion] = {"__zlibVersion", NULL},
};

static void *hostLibHandle;

/* Reentry dispatchers: the host calls these (via the InvokeProc loop) to
 * run a guest callback during inflateBack. Registered once in init(). */
static void reentry_in_func(void *callback, void *args, void *ret) {
    typedef unsigned int (*Fn)(void * /*in_desc*/, unsigned char ** /*buf*/);
    void **a = (void **) args;
    *(unsigned int *) ret =
        ((Fn) callback)(*(void **) a[0], *(unsigned char ***) a[1]);
}

static void reentry_out_func(void *callback, void *args, void *ret) {
    typedef int (*Fn)(void * /*out_desc*/, unsigned char * /*buf*/, unsigned int /*len*/);
    void **a = (void **) args;
    *(int *) ret =
        ((Fn) callback)(*(void **) a[0], *(unsigned char **) a[1], *(unsigned int *) a[2]);
}

static __attribute__((constructor(102))) void init(void) {
    hostLibHandle = LoadLibrary("libZlibThunkHost.so", RTLD_NOW);
    if (hostLibHandle == NULL) {
        fprintf(stderr, "ZlibThunk: failed to load libZlibThunkHost.so: %s\n",
                GetLibraryError());
        abort();
    }

    for (int i = 0; i < HZ_COUNT; i++) {
        hostProcs[i].proc = GetProcAddress(hostLibHandle, hostProcs[i].name);
        if (hostProcs[i].proc == NULL) {
            fprintf(stderr, "ZlibThunk: failed to resolve %s: %s\n", hostProcs[i].name,
                    GetLibraryError());
            abort();
        }
    }

    /* Register the reentry dispatchers; order MUST match the host's DispatcherIndex. */
    void *dispatchers[] = {
        (void *) reentry_in_func,
        (void *) reentry_out_func,
    };
    void *args[] = {&dispatchers[0], &dispatchers[1]};
    InvocationArguments ia = {
        .proc = hostProcs[HZ___initialize].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

uLong adler32(uLong a0, const Bytef * a1, uInt a2) {
    void *args[] = {&a0, &a1, &a2};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_adler32].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong adler32_combine(uLong a0, uLong a1, z_off_t a2) {
    void *args[] = {&a0, &a1, &a2};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_adler32_combine].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong adler32_combine64(uLong a0, uLong a1, z_off64_t a2) {
    void *args[] = {&a0, &a1, &a2};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_adler32_combine64].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong adler32_z(uLong a0, const Bytef * a1, z_size_t a2) {
    void *args[] = {&a0, &a1, &a2};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_adler32_z].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int compress(Bytef * a0, uLongf * a1, const Bytef * a2, uLong a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_compress].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int compress2(Bytef * a0, uLongf * a1, const Bytef * a2, uLong a3, int a4) {
    void *args[] = {&a0, &a1, &a2, &a3, &a4};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_compress2].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong compressBound(uLong a0) {
    void *args[] = {&a0};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_compressBound].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong crc32(uLong a0, const Bytef * a1, uInt a2) {
    void *args[] = {&a0, &a1, &a2};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_crc32].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong crc32_combine(uLong a0, uLong a1, z_off_t a2) {
    void *args[] = {&a0, &a1, &a2};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_crc32_combine].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong crc32_combine64(uLong a0, uLong a1, z_off64_t a2) {
    void *args[] = {&a0, &a1, &a2};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_crc32_combine64].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflate(z_streamp a0, int a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflate].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong deflateBound(z_streamp a0, uLong a1) {
    void *args[] = {&a0, &a1};
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateBound].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateCopy(z_streamp a0, z_streamp a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateCopy].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateEnd(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateEnd].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateGetDictionary(z_streamp a0, Bytef * a1, uInt * a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateGetDictionary].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateInit2_(z_streamp a0, int a1, int a2, int a3, int a4, int a5, const char * a6, int a7) {
    void *args[] = {&a0, &a1, &a2, &a3, &a4, &a5, &a6, &a7};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateInit2_].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateInit_(z_streamp a0, int a1, const char * a2, int a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateInit_].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateParams(z_streamp a0, int a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateParams].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflatePending(z_streamp a0, unsigned int * a1, int * a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflatePending].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflatePrime(z_streamp a0, int a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflatePrime].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateReset(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateReset].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateResetKeep(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateResetKeep].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateSetDictionary(z_streamp a0, const Bytef * a1, uInt a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateSetDictionary].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateSetHeader(z_streamp a0, gz_headerp a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateSetHeader].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int deflateTune(z_streamp a0, int a1, int a2, int a3, int a4) {
    void *args[] = {&a0, &a1, &a2, &a3, &a4};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_deflateTune].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

const z_crc_t * get_crc_table(void) {
    const z_crc_t * ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_get_crc_table].proc,
        .args = NULL,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzbuffer(gzFile a0, unsigned int a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzbuffer].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

void gzclearerr(gzFile a0) {
    void *args[] = {&a0};
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzclearerr].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

int gzclose(gzFile a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzclose].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzclose_r(gzFile a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzclose_r].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzclose_w(gzFile a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzclose_w].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzdirect(gzFile a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzdirect].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

gzFile gzdopen(int a0, const char * a1) {
    void *args[] = {&a0, &a1};
    gzFile ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzdopen].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzeof(gzFile a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzeof].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

const char * gzerror(gzFile a0, int * a1) {
    void *args[] = {&a0, &a1};
    const char * ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzerror].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzflush(gzFile a0, int a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzflush].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

z_size_t gzfread(voidp a0, z_size_t a1, z_size_t a2, gzFile a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    z_size_t ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzfread].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

z_size_t gzfwrite(voidpc a0, z_size_t a1, z_size_t a2, gzFile a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    z_size_t ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzfwrite].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzgetc(gzFile a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzgetc].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzgetc_(gzFile a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzgetc_].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

char * gzgets(gzFile a0, char * a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    char * ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzgets].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

z_off_t gzoffset(gzFile a0) {
    void *args[] = {&a0};
    z_off_t ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzoffset].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

z_off64_t gzoffset64(gzFile a0) {
    void *args[] = {&a0};
    z_off64_t ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzoffset64].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

gzFile gzopen(const char * a0, const char * a1) {
    void *args[] = {&a0, &a1};
    gzFile ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzopen].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

gzFile gzopen64(const char * a0, const char * a1) {
    void *args[] = {&a0, &a1};
    gzFile ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzopen64].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzputc(gzFile a0, int a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzputc].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzputs(gzFile a0, const char * a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzputs].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzread(gzFile a0, voidp a1, unsigned int a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzread].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzrewind(gzFile a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzrewind].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

z_off_t gzseek(gzFile a0, z_off_t a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    z_off_t ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzseek].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

z_off64_t gzseek64(gzFile a0, z_off64_t a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    z_off64_t ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzseek64].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzsetparams(gzFile a0, int a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzsetparams].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

z_off_t gztell(gzFile a0) {
    void *args[] = {&a0};
    z_off_t ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gztell].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

z_off64_t gztell64(gzFile a0) {
    void *args[] = {&a0};
    z_off64_t ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gztell64].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzungetc(int a0, gzFile a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzungetc].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int gzwrite(gzFile a0, voidpc a1, unsigned int a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_gzwrite].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflate(z_streamp a0, int a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflate].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateBackEnd(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateBackEnd].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateBackInit_(z_streamp a0, int a1, unsigned char * a2, const char * a3, int a4) {
    void *args[] = {&a0, &a1, &a2, &a3, &a4};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateBackInit_].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

unsigned long inflateCodesUsed(z_streamp a0) {
    void *args[] = {&a0};
    unsigned long ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateCodesUsed].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateCopy(z_streamp a0, z_streamp a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateCopy].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateEnd(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateEnd].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateGetDictionary(z_streamp a0, Bytef * a1, uInt * a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateGetDictionary].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateGetHeader(z_streamp a0, gz_headerp a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateGetHeader].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateInit2_(z_streamp a0, int a1, const char * a2, int a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateInit2_].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateInit_(z_streamp a0, const char * a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateInit_].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

long inflateMark(z_streamp a0) {
    void *args[] = {&a0};
    long ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateMark].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflatePrime(z_streamp a0, int a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflatePrime].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateReset(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateReset].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateReset2(z_streamp a0, int a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateReset2].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateResetKeep(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateResetKeep].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateSetDictionary(z_streamp a0, const Bytef * a1, uInt a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateSetDictionary].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateSync(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateSync].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateSyncPoint(z_streamp a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateSyncPoint].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateUndermine(z_streamp a0, int a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateUndermine].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int inflateValidate(z_streamp a0, int a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateValidate].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int uncompress(Bytef * a0, uLongf * a1, const Bytef * a2, uLong a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_uncompress].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int uncompress2(Bytef * a0, uLongf * a1, const Bytef * a2, uLong * a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_uncompress2].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

const char * zError(int a0) {
    void *args[] = {&a0};
    const char * ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_zError].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

uLong zlibCompileFlags(void) {
    uLong ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_zlibCompileFlags].proc,
        .args = NULL,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

const char * zlibVersion(void) {
    const char * ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_zlibVersion].proc,
        .args = NULL,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

/* inflateBack: in/out are guest callbacks invoked by the host routine. */
int inflateBack(z_streamp strm, in_func in, void *in_desc, out_func out, void *out_desc) {
    void *vin = (void *) in;
    void *vout = (void *) out;
    void *args[] = {&strm, &vin, &in_desc, &vout, &out_desc};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HZ_inflateBack].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}
