#!/usr/bin/env python3
"""
Generate 2-callback-style pass-through thunks for every zlib function.

Parses ZlibImport.h with clang + the symbol list, and emits:
  guest/ZlibThunk.c      - guest libz replacement: each symbol -> InvokeProc
  host/ZlibThunkHost.cpp - host adapters: unpack args -> call the REAL zlib

Special cases:
  inflateBack          -> host->guest callbacks (in_func/out_func) via reentry
  gzprintf / gzvprintf -> variadic, NOT supported by the generic marshaller
"""
import json, os, re, subprocess, sys


def fix_type(t):
    """clang desugars zlib's z_off_t/z_off64_t one level to off_t/off64_t; the
    consuming TUs only have the zlib typedefs, so map them back."""
    t = re.sub(r"\boff64_t\b", "z_off64_t", t)
    t = re.sub(r"\boff_t\b", "z_off_t", t)
    return t

HERE = os.path.dirname(os.path.abspath(__file__))
CONF = os.path.join(HERE, "Symbols.conf")
IMPORT_HDR = os.path.join(HERE, "ZlibImport.h")
GUEST_OUT = os.path.join(HERE, "guest", "ZlibThunk.c")
HOST_OUT = os.path.join(HERE, "host", "ZlibThunkHost.cpp")
CLANG = os.environ.get("CLANG", "clang-20")

VARIADIC_EXCLUDE = {"gzprintf", "gzvprintf"}
CALLBACK = {"inflateBack"}

WARNING = [
    "/*",
    " * AUTO-GENERATED by GenerateSource.py from Symbols.conf -- DO NOT EDIT.",
    " * Regenerate with:  python3 GenerateSource.py",
    " */",
    "",
]


def load_ast():
    """Parse ZlibImport.h with clang and return its JSON AST."""
    cmd = [CLANG, "-x", "c", "-Xclang", "-ast-dump=json", "-fsyntax-only",
           "-D_LARGEFILE64_SOURCE=1", IMPORT_HDR]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        sys.exit("clang AST dump failed")
    return json.loads(proc.stdout)


def load_symbols():
    syms, inblock = [], False
    for line in open(CONF):
        s = line.strip()
        if s == "[Function]":
            inblock = True
            continue
        if inblock and s:
            syms.append(s)
    return syms


def load_funcs(symset):
    d = load_ast()
    funcs = {}
    for n in d.get("inner", []):
        if n.get("kind") == "FunctionDecl" and n.get("name") in symset:
            name = n["name"]
            qt = n["type"]["qualType"]
            ret = fix_type(qt[:qt.index("(")].rstrip())  # no zlib fn returns a fn-pointer
            params = [fix_type(c["type"]["qualType"])
                      for c in n.get("inner", []) if c.get("kind") == "ParmVarDecl"]
            funcs[name] = (ret, params, bool(n.get("variadic")))
    return funcs


def gen_guest(syms, funcs, exported, generic):
    L = list(WARNING)
    w = L.append
    w('#include "../ZlibImport.h"')
    w('#include "../../2-callback/guest/GuestRuntime.h"')
    w("")
    w("#include <dlfcn.h>")
    w("#include <stddef.h>")
    w("#include <stdio.h>")
    w("#include <stdlib.h>")
    w("")
    # host proc table
    w("enum HostProcIndex {")
    w("    HZ___initialize,")
    for f in exported:
        w("    HZ_%s," % f)
    w("    HZ_COUNT,")
    w("};")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    void *proc;")
    w("} HostProc;")
    w("")
    w("static HostProc hostProcs[HZ_COUNT] = {")
    w('    [HZ___initialize] = {"__initialize", NULL},')
    for f in exported:
        w('    [HZ_%s] = {"__%s", NULL},' % (f, f))
    w("};")
    w("")
    w("static void *hostLibHandle;")
    w("")
    # reentry dispatchers for inflateBack's in_func / out_func callbacks
    w("/* Reentry dispatchers: the host calls these (via the InvokeProc loop) to")
    w(" * run a guest callback during inflateBack. Registered once in init(). */")
    w("static void reentry_in_func(void *callback, void *args, void *ret) {")
    w("    typedef unsigned int (*Fn)(void * /*in_desc*/, unsigned char ** /*buf*/);")
    w("    void **a = (void **) args;")
    w("    *(unsigned int *) ret =")
    w("        ((Fn) callback)(*(void **) a[0], *(unsigned char ***) a[1]);")
    w("}")
    w("")
    w("static void reentry_out_func(void *callback, void *args, void *ret) {")
    w("    typedef int (*Fn)(void * /*out_desc*/, unsigned char * /*buf*/, unsigned int /*len*/);")
    w("    void **a = (void **) args;")
    w("    *(int *) ret =")
    w("        ((Fn) callback)(*(void **) a[0], *(unsigned char **) a[1], *(unsigned int *) a[2]);")
    w("}")
    w("")
    # constructor (priority 102: after GuestRuntime's 101)
    w("static __attribute__((constructor(102))) void init(void) {")
    w('    hostLibHandle = LoadLibrary("libZlibThunkHost.so", RTLD_NOW);')
    w("    if (hostLibHandle == NULL) {")
    w('        fprintf(stderr, "ZlibThunk: failed to load libZlibThunkHost.so: %s\\n",')
    w("                GetLibraryError());")
    w("        abort();")
    w("    }")
    w("")
    w("    for (int i = 0; i < HZ_COUNT; i++) {")
    w("        hostProcs[i].proc = GetProcAddress(hostLibHandle, hostProcs[i].name);")
    w("        if (hostProcs[i].proc == NULL) {")
    w('            fprintf(stderr, "ZlibThunk: failed to resolve %s: %s\\n", hostProcs[i].name,')
    w("                    GetLibraryError());")
    w("            abort();")
    w("        }")
    w("    }")
    w("")
    w("    /* Register the reentry dispatchers; order MUST match the host's DispatcherIndex. */")
    w("    void *dispatchers[] = {")
    w("        (void *) reentry_in_func,")
    w("        (void *) reentry_out_func,")
    w("    };")
    w("    void *args[] = {&dispatchers[0], &dispatchers[1]};")
    w("    InvocationArguments ia = {")
    w("        .proc = hostProcs[HZ___initialize].proc,")
    w("        .args = args,")
    w("        .ret  = NULL,")
    w("    };")
    w("    InvokeProc(&ia);")
    w("}")
    w("")
    # generic function bodies
    for f in generic:
        ret, params, _ = funcs[f]
        is_void = (ret == "void")
        names = ["a%d" % i for i in range(len(params))]
        sig = ", ".join("%s %s" % (p, n) for p, n in zip(params, names)) or "void"
        w("%s %s(%s) {" % (ret, f, sig))
        if params:
            w("    void *args[] = {%s};" % ", ".join("&%s" % n for n in names))
        argref = "args" if params else "NULL"
        if is_void:
            w("    InvocationArguments ia = {")
            w("        .proc = hostProcs[HZ_%s].proc," % f)
            w("        .args = %s," % argref)
            w("        .ret  = NULL,")
            w("    };")
            w("    InvokeProc(&ia);")
        else:
            w("    %s ret;" % ret)
            w("    InvocationArguments ia = {")
            w("        .proc = hostProcs[HZ_%s].proc," % f)
            w("        .args = %s," % argref)
            w("        .ret  = &ret,")
            w("    };")
            w("    InvokeProc(&ia);")
            w("    return ret;")
        w("}")
        w("")
    # inflateBack (hand-written callback case)
    w("/* inflateBack: in/out are guest callbacks invoked by the host routine. */")
    w("int inflateBack(z_streamp strm, in_func in, void *in_desc, out_func out, void *out_desc) {")
    w("    void *vin = (void *) in;")
    w("    void *vout = (void *) out;")
    w("    void *args[] = {&strm, &vin, &in_desc, &vout, &out_desc};")
    w("    int ret;")
    w("    InvocationArguments ia = {")
    w("        .proc = hostProcs[HZ_inflateBack].proc,")
    w("        .args = args,")
    w("        .ret  = &ret,")
    w("    };")
    w("    InvokeProc(&ia);")
    w("    return ret;")
    w("}")
    w("")
    return "\n".join(L)


def gen_host(syms, funcs, exported, generic):
    L = list(WARNING)
    w = L.append
    w('#include "../ZlibImport.h"')
    w('#include "../../2-callback/host/Invocation.h"')
    w("")
    w("#include <cstddef>")
    w("#include <cstdint>")
    w("")
    w("typedef struct {")
    w("    void *proc;     /* guest reentry dispatcher */")
    w("    void *callback; /* guest callback           */")
    w("    void *args;")
    w("    void *ret;")
    w("} ReentryArguments;")
    w("")
    w("enum DispatcherIndex {")
    w("    DI_in_func,")
    w("    DI_out_func,")
    w("};")
    w("")
    w("static void *gDispatchers[2];")
    w("")
    w("/* Boundary between guest and host address space (set by HostRuntime): a")
    w(" * pointer below it is a guest function, at/above it is a host function. */")
    w('extern "C" void *qemu_address;')
    w("")
    w('extern "C" void __initialize(void **args, void *ret) {')
    w("    (void) ret;")
    w("    for (int i = 0; i < sizeof(gDispatchers) / sizeof(gDispatchers[0]); i++) {")
    w("        gDispatchers[i] = *(void **) args[i];")
    w("    }")
    w("}")
    w("")
    # callback trampolines for inflateBack (thread_local guest callbacks)
    w("/* The C library calls these from host zlib; each re-enters the guest with")
    w(" * the saved guest callback. Single in-flight inflateBack per thread. */")
    w("static thread_local void *tlsIn;")
    w("static thread_local void *tlsOut;")
    w("")
    w("static unsigned int host_in(void *in_desc, unsigned char **buf) {")
    w("    void *a[] = {&in_desc, &buf};")
    w("    unsigned int ret = 0;")
    w("    ReentryArguments ra = {gDispatchers[DI_in_func], tlsIn, a, &ret};")
    w("    lore::utils::Invocation::reenter(&ra);")
    w("    return ret;")
    w("}")
    w("")
    w("static int host_out(void *out_desc, unsigned char *buf, unsigned int len) {")
    w("    void *a[] = {&out_desc, &buf, &len};")
    w("    int ret = 0;")
    w("    ReentryArguments ra = {gDispatchers[DI_out_func], tlsOut, a, &ret};")
    w("    lore::utils::Invocation::reenter(&ra);")
    w("    return ret;")
    w("}")
    w("")
    # generic adapters
    for f in generic:
        ret, params, _ = funcs[f]
        is_void = (ret == "void")
        call_args = ", ".join("*(%s *) args[%d]" % (p, i) for i, p in enumerate(params))
        w('extern "C" void __%s(void **args, void *ret) {' % f)
        if not params:
            w("    (void) args;")
        if is_void:
            w("    (void) ret;")
            w("    %s(%s);" % (f, call_args))
        else:
            w("    *(%s *) ret = %s(%s);" % (ret, f, call_args))
        w("}")
        w("")
    # inflateBack adapter
    w('extern "C" void __inflateBack(void **args, void *ret) {')
    w("    z_streamp strm = *(z_streamp *) args[0];")
    w("    void *in       = *(void **)     args[1];")
    w("    void *in_desc  = *(void **)     args[2];")
    w("    void *out      = *(void **)     args[3];")
    w("    void *out_desc = *(void **)     args[4];")
    w("")
    w("    /* Only a guest callback needs to be routed through a trampoline; a host")
    w("     * function pointer is called directly. tls is set right before the call")
    w("     * and only read when the matching trampoline is installed, so it needs")
    w("     * no save/restore. */")
    w("    in_func hin = (in_func) in;")
    w("    if ((uintptr_t) in < (uintptr_t) qemu_address) {")
    w("        tlsIn = in;")
    w("        hin = host_in;")
    w("    }")
    w("    out_func hout = (out_func) out;")
    w("    if ((uintptr_t) out < (uintptr_t) qemu_address) {")
    w("        tlsOut = out;")
    w("        hout = host_out;")
    w("    }")
    w("    *(int *) ret = inflateBack(strm, hin, in_desc, hout, out_desc);")
    w("}")
    w("")
    return "\n".join(L)


def main():
    syms = load_symbols()
    funcs = load_funcs(set(syms))
    missing = [s for s in syms if s not in funcs]
    if missing:
        print("ERROR unresolved:", missing, file=sys.stderr)
        sys.exit(1)

    exported = [f for f in syms if f not in VARIADIC_EXCLUDE]
    generic = [f for f in exported if f not in CALLBACK]

    open(GUEST_OUT, "w").write(gen_guest(syms, funcs, exported, generic))
    open(HOST_OUT, "w").write(gen_host(syms, funcs, exported, generic))

    print("generated %d generic + %d callback funcs; excluded variadic: %s"
          % (len(generic), len(CALLBACK), sorted(VARIADIC_EXCLUDE)))


if __name__ == "__main__":
    main()
