/*
 * AUTO-GENERATED by GenerateSource.py -- DO NOT EDIT.
 * Regenerate with:  python3 GenerateSource.py
 */

#include "../GLImport.h"
#include "../../2-callback/guest/GuestRuntime.h"

#include <dlfcn.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

enum HostProcIndex {
    HP_glBegin,
    HP_glBlendFunc,
    HP_glClear,
    HP_glClearColor,
    HP_glColor4f,
    HP_glDisable,
    HP_glEnable,
    HP_glEnd,
    HP_glFrustum,
    HP_glHint,
    HP_glLineWidth,
    HP_glLoadIdentity,
    HP_glMatrixMode,
    HP_glPointSize,
    HP_glPopMatrix,
    HP_glPushMatrix,
    HP_glRotatef,
    HP_glTranslatef,
    HP_glVertex3f,
    HP_glViewport,
    HP_glXChooseVisual,
    HP_glXCreateContext,
    HP_glXDestroyContext,
    HP_glXMakeCurrent,
    HP_glXSwapBuffers,
    HP_COUNT,
};

typedef struct {
    const char *name;
    void *proc;
} HostProc;

static HostProc hostProcs[HP_COUNT] = {
    [HP_glBegin] = {"__glBegin", NULL},
    [HP_glBlendFunc] = {"__glBlendFunc", NULL},
    [HP_glClear] = {"__glClear", NULL},
    [HP_glClearColor] = {"__glClearColor", NULL},
    [HP_glColor4f] = {"__glColor4f", NULL},
    [HP_glDisable] = {"__glDisable", NULL},
    [HP_glEnable] = {"__glEnable", NULL},
    [HP_glEnd] = {"__glEnd", NULL},
    [HP_glFrustum] = {"__glFrustum", NULL},
    [HP_glHint] = {"__glHint", NULL},
    [HP_glLineWidth] = {"__glLineWidth", NULL},
    [HP_glLoadIdentity] = {"__glLoadIdentity", NULL},
    [HP_glMatrixMode] = {"__glMatrixMode", NULL},
    [HP_glPointSize] = {"__glPointSize", NULL},
    [HP_glPopMatrix] = {"__glPopMatrix", NULL},
    [HP_glPushMatrix] = {"__glPushMatrix", NULL},
    [HP_glRotatef] = {"__glRotatef", NULL},
    [HP_glTranslatef] = {"__glTranslatef", NULL},
    [HP_glVertex3f] = {"__glVertex3f", NULL},
    [HP_glViewport] = {"__glViewport", NULL},
    [HP_glXChooseVisual] = {"__glXChooseVisual", NULL},
    [HP_glXCreateContext] = {"__glXCreateContext", NULL},
    [HP_glXDestroyContext] = {"__glXDestroyContext", NULL},
    [HP_glXMakeCurrent] = {"__glXMakeCurrent", NULL},
    [HP_glXSwapBuffers] = {"__glXSwapBuffers", NULL},
};

static void *hostLibHandle;

static __attribute__((constructor(102))) void init(void) {
    hostLibHandle = LoadLibrary("libGLThunkHost.so", RTLD_NOW);
    if (hostLibHandle == NULL) {
        fprintf(stderr, "GL: failed to load libGLThunkHost.so: %s\n", GetLibraryError());
        abort();
    }

    for (int i = 0; i < HP_COUNT; i++) {
        hostProcs[i].proc = GetProcAddress(hostLibHandle, hostProcs[i].name);
        if (hostProcs[i].proc == NULL) {
            fprintf(stderr, "GL: failed to resolve %s: %s\n", hostProcs[i].name,
                    GetLibraryError());
            abort();
        }
    }
}

void glBegin(GLenum a0) {
    void *args[] = {&a0};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glBegin].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glBlendFunc(GLenum a0, GLenum a1) {
    void *args[] = {&a0, &a1};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glBlendFunc].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glClear(GLbitfield a0) {
    void *args[] = {&a0};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glClear].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glClearColor(GLclampf a0, GLclampf a1, GLclampf a2, GLclampf a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glClearColor].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glColor4f(GLfloat a0, GLfloat a1, GLfloat a2, GLfloat a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glColor4f].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glDisable(GLenum a0) {
    void *args[] = {&a0};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glDisable].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glEnable(GLenum a0) {
    void *args[] = {&a0};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glEnable].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glEnd(void) {
    InvocationArguments ia = {
        .proc = hostProcs[HP_glEnd].proc,
        .args = NULL,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glFrustum(GLdouble a0, GLdouble a1, GLdouble a2, GLdouble a3, GLdouble a4, GLdouble a5) {
    void *args[] = {&a0, &a1, &a2, &a3, &a4, &a5};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glFrustum].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glHint(GLenum a0, GLenum a1) {
    void *args[] = {&a0, &a1};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glHint].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glLineWidth(GLfloat a0) {
    void *args[] = {&a0};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glLineWidth].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glLoadIdentity(void) {
    InvocationArguments ia = {
        .proc = hostProcs[HP_glLoadIdentity].proc,
        .args = NULL,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glMatrixMode(GLenum a0) {
    void *args[] = {&a0};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glMatrixMode].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glPointSize(GLfloat a0) {
    void *args[] = {&a0};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glPointSize].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glPopMatrix(void) {
    InvocationArguments ia = {
        .proc = hostProcs[HP_glPopMatrix].proc,
        .args = NULL,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glPushMatrix(void) {
    InvocationArguments ia = {
        .proc = hostProcs[HP_glPushMatrix].proc,
        .args = NULL,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glRotatef(GLfloat a0, GLfloat a1, GLfloat a2, GLfloat a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glRotatef].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glTranslatef(GLfloat a0, GLfloat a1, GLfloat a2) {
    void *args[] = {&a0, &a1, &a2};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glTranslatef].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glVertex3f(GLfloat a0, GLfloat a1, GLfloat a2) {
    void *args[] = {&a0, &a1, &a2};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glVertex3f].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

void glViewport(GLint a0, GLint a1, GLsizei a2, GLsizei a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glViewport].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

XVisualInfo * glXChooseVisual(Display * a0, int a1, int * a2) {
    void *args[] = {&a0, &a1, &a2};
    XVisualInfo * ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_glXChooseVisual].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

GLXContext glXCreateContext(Display * a0, XVisualInfo * a1, GLXContext a2, int a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    GLXContext ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_glXCreateContext].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

void glXDestroyContext(Display * a0, GLXContext a1) {
    void *args[] = {&a0, &a1};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glXDestroyContext].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}

int glXMakeCurrent(Display * a0, GLXDrawable a1, GLXContext a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_glXMakeCurrent].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

void glXSwapBuffers(Display * a0, GLXDrawable a1) {
    void *args[] = {&a0, &a1};
    InvocationArguments ia = {
        .proc = hostProcs[HP_glXSwapBuffers].proc,
        .args = args,
        .ret  = NULL,
    };
    InvokeProc(&ia);
}
