/*
 * AUTO-GENERATED by GenerateSource.py -- DO NOT EDIT.
 * Regenerate with:  python3 GenerateSource.py
 */

#include "../X11Import.h"
#include "../../2-callback/guest/GuestRuntime.h"

#include <dlfcn.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

enum HostProcIndex {
    HP_XCloseDisplay,
    HP_XCreateColormap,
    HP_XCreateWindow,
    HP_XDestroyWindow,
    HP_XInternAtom,
    HP_XLookupKeysym,
    HP_XMapWindow,
    HP_XNextEvent,
    HP_XOpenDisplay,
    HP_XPending,
    HP_XSetWMProtocols,
    HP_XStoreName,
    HP_COUNT,
};

typedef struct {
    const char *name;
    void *proc;
} HostProc;

static HostProc hostProcs[HP_COUNT] = {
    [HP_XCloseDisplay] = {"__XCloseDisplay", NULL},
    [HP_XCreateColormap] = {"__XCreateColormap", NULL},
    [HP_XCreateWindow] = {"__XCreateWindow", NULL},
    [HP_XDestroyWindow] = {"__XDestroyWindow", NULL},
    [HP_XInternAtom] = {"__XInternAtom", NULL},
    [HP_XLookupKeysym] = {"__XLookupKeysym", NULL},
    [HP_XMapWindow] = {"__XMapWindow", NULL},
    [HP_XNextEvent] = {"__XNextEvent", NULL},
    [HP_XOpenDisplay] = {"__XOpenDisplay", NULL},
    [HP_XPending] = {"__XPending", NULL},
    [HP_XSetWMProtocols] = {"__XSetWMProtocols", NULL},
    [HP_XStoreName] = {"__XStoreName", NULL},
};

static void *hostLibHandle;

static __attribute__((constructor(102))) void init(void) {
    hostLibHandle = LoadLibrary("libX11ThunkHost.so", RTLD_NOW);
    if (hostLibHandle == NULL) {
        fprintf(stderr, "X11: failed to load libX11ThunkHost.so: %s\n", GetLibraryError());
        abort();
    }

    for (int i = 0; i < HP_COUNT; i++) {
        hostProcs[i].proc = GetProcAddress(hostLibHandle, hostProcs[i].name);
        if (hostProcs[i].proc == NULL) {
            fprintf(stderr, "X11: failed to resolve %s: %s\n", hostProcs[i].name,
                    GetLibraryError());
            abort();
        }
    }
}

int XCloseDisplay(Display * a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XCloseDisplay].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

Colormap XCreateColormap(Display * a0, Window a1, Visual * a2, int a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    Colormap ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XCreateColormap].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

Window XCreateWindow(Display * a0, Window a1, int a2, int a3, unsigned int a4, unsigned int a5, unsigned int a6, int a7, unsigned int a8, Visual * a9, unsigned long a10, XSetWindowAttributes * a11) {
    void *args[] = {&a0, &a1, &a2, &a3, &a4, &a5, &a6, &a7, &a8, &a9, &a10, &a11};
    Window ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XCreateWindow].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int XDestroyWindow(Display * a0, Window a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XDestroyWindow].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

Atom XInternAtom(Display * a0, const char * a1, int a2) {
    void *args[] = {&a0, &a1, &a2};
    Atom ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XInternAtom].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

KeySym XLookupKeysym(XKeyEvent * a0, int a1) {
    void *args[] = {&a0, &a1};
    KeySym ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XLookupKeysym].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int XMapWindow(Display * a0, Window a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XMapWindow].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int XNextEvent(Display * a0, XEvent * a1) {
    void *args[] = {&a0, &a1};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XNextEvent].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

Display * XOpenDisplay(const char * a0) {
    void *args[] = {&a0};
    Display * ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XOpenDisplay].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int XPending(Display * a0) {
    void *args[] = {&a0};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XPending].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int XSetWMProtocols(Display * a0, Window a1, Atom * a2, int a3) {
    void *args[] = {&a0, &a1, &a2, &a3};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XSetWMProtocols].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}

int XStoreName(Display * a0, Window a1, const char * a2) {
    void *args[] = {&a0, &a1, &a2};
    int ret;
    InvocationArguments ia = {
        .proc = hostProcs[HP_XStoreName].proc,
        .args = args,
        .ret  = &ret,
    };
    InvokeProc(&ia);
    return ret;
}
